package exceptions;


/**
 * Exception generated by line in a VCF file
 * @author Julien Lajugie
 */
public abstract class VCFException extends Exception {

	private static final long serialVersionUID = 8840126119819018297L;	// generated ID

	
	/**
	 * Creates an instance of {@link VCFException}
	 * @param message detail message of the exception
	 */
	public VCFException(String message) {
		super(message);	
	}
}
